import "./globals.css";
import type { Metadata } from "next";
import localFont from "next/font/local";

const myFont = localFont({
  src: [
    {
      path: "../fonts/Museo_Slab_100.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../fonts/Museo_Slab_300.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../fonts/Museo_Slab_500.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../fonts/Museo_Slab_700.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../fonts/Museo_Slab_900.otf",
      weight: "700",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={myFont.className}>{children}</body>
    </html>
  );
}
